toss1:
  job.type: search
  dataset.name: sampled_wnrr_0.2
  model: complex
  
  search.type: ax
  ax_search:
    topK: 30
    record_topK: true
    num_trials: 200
    num_sobol_trials: 70
    parameters:
      - name: train.batch_size
        type: choice
        values: [128, 256, 512]
      - name: lookup_embedder.dim
        type: choice
        values: [128, 256, 512]
      - name: train.optimizer_args.lr
        type: range
        bounds: [0.0003, 1.0]
      - name: 1vsAll.rp_lambda
        type: range
        bounds: [0.0, 1.0]
      - name: complex.entity_embedder.dropout
        type: range
        bounds: [0.0, 0.75]
      - name: complex.relation_embedder.dropout
        type: range
        bounds: [0.0, 0.75]
      - name: complex.entity_embedder.regularize_weight
        type: range
        bounds: [1.0e-12, 1.0e-4]
        log_scale: True
      - name: complex.relation_embedder.regularize_weight
        type: range
        bounds: [1.0e-12, 1.0e-4]
        log_scale: True
      - name: lookup_embedder.regularize_args.p
        type: choice
        values: [2, 3]

  complex:
    entity_embedder:
      dropout: 0.3592749142853321
      regularize_weight: 4.5230047706178325e-06
    relation_embedder:
      dropout: 0.3112283826796357
      regularize_weight: 4.192985917075565e-10
  eval:
    metrics_per:
      relation_type: true
    trace_level: example
  import:
  - complex
  - reciprocal_relations_model
  lookup_embedder:
    dim: 128
    initialize: uniform_
    initialize_args:
      normal_:
        mean: 0.0
        std: 0.0005472140383629246
      uniform_:
        a: -0.28148249060722197
      xavier_normal_:
        gain: 1.0
      xavier_uniform_:
        gain: 1.0
  negative_sampling:
    implementation: batch
    num_samples:
      p: -1
  reciprocal_relations_model:
    base_model:
      type: complex
  train:
    auto_correct: true
    batch_size: 512
    loss_arg: 1.0
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      factor: 0.95
      mode: max
      patience: 5
      threshold: 0.0001
    max_epochs: 400
    type: 1vsAll
  valid:
    early_stopping:
      min_threshold:
        epochs: 50
        metric_value: 0.05
      patience: 10
  1vsAll:
    relation_prediction: True




toss2:
  job.type: search
  dataset.name: wnrr
  model: complex
  
  search.type: toss2

  toss2:
    topK: 30
    num_trials: 30
    
  complex:
    entity_embedder:
      dropout: 0.3592749142853321
      regularize_weight: 4.5230047706178325e-06
    relation_embedder:
      dropout: 0.3112283826796357
      regularize_weight: 4.192985917075565e-10
  eval:
    metrics_per:
      relation_type: true
    trace_level: example
  import:
  - complex
  - reciprocal_relations_model
  lookup_embedder:
    dim: 128
    initialize: uniform_
    initialize_args:
      normal_:
        mean: 0.0
        std: 0.0005472140383629246
      uniform_:
        a: -0.28148249060722197
      xavier_normal_:
        gain: 1.0
      xavier_uniform_:
        gain: 1.0
  negative_sampling:
    implementation: batch
    num_samples:
      p: -1
  reciprocal_relations_model:
    base_model:
      type: complex
  train:
    auto_correct: true
    batch_size: 512
    loss_arg: 1.0
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      factor: 0.95
      mode: max
      patience: 5
      threshold: 0.0001
    max_epochs: 400
    type: 1vsAll
  valid:
    early_stopping:
      min_threshold:
        epochs: 50
        metric_value: 0.05
      patience: 10
  1vsAll:
    relation_prediction: True

