stage1:
  job.type: search
  dataset.name: sampled_wnrr_0.2
  model: autosf
  
  search.type: ax
  ax_search:
    topK: 30
    record_topK: true
    num_trials: 200
    num_sobol_trials: 70
    parameters:
      - name: lookup_embedder.dim
        type: choice
        values: [128, 256]
      - name: train.optimizer_args.lr
        type: range
        bounds: [0.0003, 1.0]
        log_scale: True
      - name: 1vsAll.rp_lambda
        type: range
        bounds: [0.0, 1.0]
      - name: autosf.entity_embedder.dropout
        type: range
        bounds: [0.2, 0.7]
      - name: autosf.relation_embedder.dropout
        type: range
        bounds: [0.2, 0.7]
      - name: autosf.entity_embedder.regularize_weight
        type: range
        bounds: [1.0e-7, 1.0e-2]
        log_scale: True
      - name: autosf.relation_embedder.regularize_weight
        type: range
        bounds: [1.0e-7, 1.0e-2]
        log_scale: True

  autosf:
    A: [1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 4, 0]
    K: 4
  eval:
    batch_size: 256
    metrics_per:
      relation_type: true
    trace_level: example
  import:
  - reciprocal_relations_model
  - complex
  lookup_embedder:
    dim: 512
    initialize: uniform_
    initialize_args:
      normal_:
        mean: 0.0
        std: 0.5592429029559286
      uniform_:
        a: -0.8328168489829233
      xavier_normal_:
        gain: 1.0
      xavier_uniform_:
        gain: 1.0
    regularize_args:
      p: 3
      weighted: true
  negative_sampling:
    implementation: batch
    num_samples:
      o: 1000
      p: -1
      s: 529
  reciprocal_relations_model:
    base_model:
      type: autosf
  train:
    auto_correct: true
    batch_size: 512
    loss_arg: 1.0
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      factor: 0.95
      mode: max
      patience: 7
      threshold: 0.0001
    max_epochs: 400
    optimizer_args:
      lr: 0.18255429345236635
    type: 1vsAll
  valid:
    early_stopping:
      min_threshold:
        epochs: 50
        metric_value: 0.05
      patience: 10

  1vsAll:
    relation_prediction: True




stage2:
  job.type: search
  dataset.name: wnrr
  model: autosf
  
  search.type: kgtuner2

  kgtuner2:
    topK: 30
    num_trials: 30
    
  autosf:
    A: [1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 4, 0]
    K: 4
  eval:
    batch_size: 256
    metrics_per:
      relation_type: true
    trace_level: example
  import:
  - reciprocal_relations_model
  - complex
  lookup_embedder:
    dim: 1024
    initialize: uniform_
    initialize_args:
      normal_:
        mean: 0.0
        std: 0.5592429029559286
      uniform_:
        a: -0.8328168489829233
      xavier_normal_:
        gain: 1.0
      xavier_uniform_:
        gain: 1.0
    regularize_args:
      p: 3
      weighted: true
  negative_sampling:
    implementation: batch
    num_samples:
      o: 1000
      p: -1
      s: 529
  reciprocal_relations_model:
    base_model:
      type: autosf
  train:
    auto_correct: true
    batch_size: 1024
    loss_arg: 1.0
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      factor: 0.95
      mode: max
      patience: 7
      threshold: 0.0001
    max_epochs: 400
    optimizer_args:
      lr: 0.18255429345236635
    type: 1vsAll
  valid:
    early_stopping:
      min_threshold:
        epochs: 50
        metric_value: 0.05
      patience: 10

  1vsAll:
    relation_prediction: True

