stage1:
  job.type: search
  dataset.name: sampled_fb15k-237_0.2
  model: complex
  
  search.type: ax
  ax_search:
    topK: 40
    record_topK: true
    num_trials: 200
    num_sobol_trials: 70
    parameters:
      - name: train.batch_size
        type: choice
        values: [128, 256, 512]
      - name: lookup_embedder.dim
        type: choice
        values: [128, 256, 512]
      - name: train.optimizer_args.lr
        type: range
        bounds: [0.0003, 1.0]
      - name: 1vsAll.rp_lambda
        type: range
        bounds: [0.0, 1.0]
      - name: complex.entity_embedder.dropout
        type: range
        bounds: [0.0, 0.75]
      - name: complex.relation_embedder.dropout
        type: range
        bounds: [0.0, 0.75]
      - name: complex.entity_embedder.regularize_weight
        type: range
        bounds: [1.0e-12, 1.0e-4]
        log_scale: True
      - name: complex.relation_embedder.regularize_weight
        type: range
        bounds: [1.0e-12, 1.0e-4]
        log_scale: True
      - name: lookup_embedder.regularize_args.p
        type: choice
        values: [2, 3]

  complex:
    entity_embedder:
      dropout: 0.5
      regularize_weight: 1.3408200403806817e-08
    relation_embedder:
      dropout: 0.22684140529516872
      regularize_weight: 8.266519211068944e-14
  eval:
    batch_size: 256
    metrics_per:
      relation_type: true
    trace_level: example
  import:
  - reciprocal_relations_model
  - complex
  lookup_embedder:
    dim: 256
    initialize: uniform_
    initialize_args:
      normal_:
        mean: 0.0
        std: 0.5592429029559286
      uniform_:
        a: -0.8328168489829233
      xavier_normal_:
        gain: 1.0
      xavier_uniform_:
        gain: 1.0
    regularize_args:
      p: 3
      weighted: true
  model: reciprocal_relations_model
  negative_sampling:
    implementation: batch
    num_samples:
      o: 1000
      p: -1
      s: 529
  reciprocal_relations_model:
    base_model:
      type: complex
  train:
    auto_correct: true
    batch_size: 1024
    loss_arg: 1.0
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      factor: 0.95
      mode: max
      patience: 7
      threshold: 0.0001
    max_epochs: 400
    optimizer_args:
      lr: 0.18255429345236635
    type: negative_sampling
  valid:
    early_stopping:
      min_threshold:
        epochs: 50
        metric_value: 0.05
      patience: 10

  1vsAll:
    relation_prediction: True




stage2:
  job.type: search
  dataset.name: fb15k-237
  model: complex
  
  search.type: kgtuner2

  kgtuner2:
    topK: 40
    num_trials: 40
    
  complex:
    entity_embedder:
      dropout: 0.5
      regularize_weight: 1.3408200403806817e-08
    relation_embedder:
      dropout: 0.22684140529516872
      regularize_weight: 8.266519211068944e-14
  eval:
    batch_size: 256
    metrics_per:
      relation_type: true
    trace_level: example
  import:
  - reciprocal_relations_model
  - complex
  lookup_embedder:
    dim: 256
    initialize: uniform_
    initialize_args:
      normal_:
        mean: 0.0
        std: 0.5592429029559286
      uniform_:
        a: -0.8328168489829233
      xavier_normal_:
        gain: 1.0
      xavier_uniform_:
        gain: 1.0
    regularize_args:
      p: 3
      weighted: true
  model: reciprocal_relations_model
  negative_sampling:
    implementation: batch
    num_samples:
      o: 1000
      p: -1
      s: 529
  reciprocal_relations_model:
    base_model:
      type: complex
  train:
    auto_correct: true
    batch_size: 1024
    loss_arg: 1.0
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      factor: 0.95
      mode: max
      patience: 7
      threshold: 0.0001
    max_epochs: 400
    optimizer_args:
      lr: 0.18255429345236635
    type: negative_sampling
  valid:
    early_stopping:
      min_threshold:
        epochs: 50
        metric_value: 0.05
      patience: 10

  1vsAll:
    relation_prediction: True

