job.type: search
search.type: ax

dataset.name: wnrr
model: autosf
valid.metric: mean_reciprocal_rank_filtered_with_test

ax_search:
  num_trials: 150
  num_sobol_trials: 100  # remaining trials are Bayesian
  parameters:
    - name: train.batch_size
      type: choice
      values: [256, 512, 1024]
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.0003, 1.0]
    - name: 1vsAll.rp_lambda
      type: range
      bounds: [0.0, 1.0]
    - name: autosf.entity_embedder.dropout
      type: range
      bounds: [0.0, 0.7]
    - name: autosf.relation_embedder.dropout
      type: range
      bounds: [0.0, 0.7]
    - name: autosf.entity_embedder.regularize_weight
      type: range
      bounds: [1.0e-18, 1.0e-4]
    - name: autosf.relation_embedder.regularize_weight
      type: range
      bounds: [1.0e-18, 1.0e-4]
    - name: lookup_embedder.dim
      type: choice
      values: [128, 256, 512]
    - name: lookup_embedder.initialize_args.normal_.std
      type: range
      bounds: [0.2, 1.0]
    - name: lookup_embedder.initialize_args.uniform_.a
      type: range
      bounds: [-1.0, 1.0]
    - name: lookup_embedder.regularize_args.p
      type: choice
      values: [2, 3]


autosf:
  A: [2,1,0,0, 2,0,0,0, 0,0,0,3, 0,0,4,0]
  K: 4
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- reciprocal_relations_model
- autosf
lookup_embedder:
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    weighted: true
model: autosf
negative_sampling:
  implementation: batch
  num_samples:
    o: 1000
    p: -1
    s: 529
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer:
    default:
      type: Adam
  type: 1vsAll
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 0
1vsAll:
  relation_prediction: True

