job.type: search
search.type: ax

dataset.name: fb15k-237
model: autosf
valid.metric: mean_reciprocal_rank_filtered_with_test

ax_search:
  num_trials: 30
  num_sobol_trials: 10  # remaining trials are Bayesian
  parameters:
    - name: train.batch_size
      type: choice
      values: [256, 512, 1024]
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.0003, 1.0]
    - name: 1vsAll.rp_lambda
      type: range
      bounds: [0.0, 1.0]


autosf:
  entity_embedder:
    dropout: 0.5
    regularize_weight: 1.3408200403806817e-08
  relation_embedder:
    dropout: 0.22684140529516872
    regularize_weight: 8.266519211068944e-14
  A: [1,0,0,4, 0,2,0,0, 0,0,3,0, 0,0,0,4]
  K: 4

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- reciprocal_relations_model
- autosf
lookup_embedder:
  dim: 256
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.5592429029559286
    uniform_:
      a: -0.8328168489829233
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
    weighted: true
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
  num_samples:
    o: 1000
    p: -1
    s: 529
reciprocal_relations_model:
  base_model:
    type: autosf
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.18255429345236635
  type: negative_sampling
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 0

