job.type: train
dataset.name: toy
# dataset.biokg: true

train:
  optimizer.default:
    type: Adagrad
    args:
      lr: 0.2
  type: negative_sampling
  batch_size: 32
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4

model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1

negative_sampling:
  num_samples:
    s: 8
    p: 0          # -1 means: same as s
    o: 5        # -1 means: same as s